### PR TITLE
Automatically collect/generate proxies from WSL /usr/bin

### PR DESCRIPTION
**Pull request by flowstatedev**

### CODE REVIEW

**Comment by watzon** [comment]
My only hangup with this is that someone might not want all of the files in `/usr/bin` proxied. I'm fairly certain there's at least a few naming conflicts as well. It might be a better idea if, instead of automatically generating them, we just allowed them to auto-generate several at a time by doing the following:

1. Run the script `proxygen.bat` or whatever
2. The script asks for the names of the programs you want to proxy
3. The user submits a list of any number of programs
4. The script runs `which` to see where the program is. Keep in mind that it could be in `/usr/bin`, `/usr/local/bin`, `~/.local/applications`, `/opt` or any number of other places as long as they're on the PATH
5. Proxy files are generated with the full path to the file

Optionally it would be nice if they could include the full path to the file already, just in case it's not on the PATH. If they use an absolute path instead of a program name step 4 should be skipped.

Thanks for the PR!

**Comment by flowstatedev** [comment]
No worries!

Yeah, I thought about that -- I basically just made the script to fulfill issue #11. 

The best of both worlds would be if the script took input (either from the command line or stdin) and you can specify names of programs including wildcards (which would ofc happen naturally). So if you really wanted to generate proxies for all programs /usr/bin/, you could specify "/usr/bin/*"

I'll take a look at improving this at some point.

**Comment by flowstatedev** [comment]
Alright, I made the following changes:

* Renamed script to proxygen.cmd
* Allow user to specify program names either on command line or from stdin/file

**Comment by watzon** [comment]
@flowstatedev is any vaidation being done on the paths? If not we should definitely validate that the programs they're attempting to proxy actually exist. I'll put this up for review prior to merging it because I don't have Windows currently and can't verify that things are working myself.

**Comment by flowstatedev** [comment]
I purposely wrote it so that you could generate proxies from programs that don't exist (yet). If the program exists, then `which` is used to grab the absolute path. Otherwise, the program name is used as-is.

I could change it so it doesn't generate proxies for non-existent programs.

**Comment by watzon** [comment]
Hmm maybe we could leave it as-is for now and see what happens

**Comment by flowstatedev** [comment]
No worries! Hope it's useful :).

I already made some edits to display an error message and skip generating the proxy for non-existent programs. If it's an issue for people it could be optional behaviour (with something like an "-f" flag to force proxies to be generated even if the program doesn't exist.)

**Comment by watzon** [comment]
Or maybe a warning would be enough

**Pull request merged**
